name: Code Quality & Standards Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: yarn install

      - name: Lint code
        run: yarn lint

      - name: Check code formatting
        run: yarn format:check

      - name: Check conventional commits
        uses: webiny/action-conventional-commits@v1.1.0
